# Generated by Django 4.2.7 on 2023-11-25 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkin',
            old_name='employee',
            new_name='employee_id',
        ),
    ]
